name: GitHub Actions Demo
on: [push]
jobs:
    Run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: not sure what exactly this names
              uses: actions/checkout@v3
            - run: npm install
            - run: npm run test
            - echo: tests have passed -> autodeploy should be triggered
